[package]
name = "srml-finality-tracker"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
parity-codec = { version = "3.2", default-features = false }
inherents = { package = "substrate-inherents", git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee-v1.0" }
rstd = { package = "sr-std", git = "https://github.com/yeeco/substrate.git", default-features = false, branch = "yee-v1.0" }
primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", default-features = false, branch = "yee-v1.0" }
srml-support = { git = "https://github.com/yeeco/substrate.git", default-features = false, branch = "yee-v1.0" }
system = { package = "srml-system", git = "https://github.com/yeeco/substrate.git", default-features = false, branch = "yee-v1.0" }

[dev-dependencies]
substrate-primitives = { git = "https://github.com/yeeco/substrate.git", default-features = false , branch = "yee-v1.0" }
sr-io = { package = "sr-io", git = "https://github.com/yeeco/substrate.git", default-features = false , branch = "yee-v1.0" }
lazy_static = "1.0"
parking_lot = "0.7"

[features]
default = ["std"]
std = [
	"serde/std",
	"parity-codec/std",
	"rstd/std",
	"srml-support/std",
	"primitives/std",
	"system/std",
	"inherents/std",
]
